name: CI
on: [push]
jobs:
  fuzz:
    runs-on: ubuntu-latest
    container: kreato/builder:latest
    steps:
      - name: Do all the things
        run: git clone https://github.com/${{ github.repository }} && cd ${{ github.event.repository.name }} && git checkout ${{ github.ref_name }} && chmod +x ./build-everything.sh && ./build-everything.sh  
