name: CI
on: [push]
jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Do the chroot things
        run: wget https://nightly.link/kreatolinux/nyaa3/workflows/build-rootfs/master/builder-rootfs.zip && mkdir kreato && unzip builder-rootfs.zip -d temp && tar -zxf ./temp/*.tar.gz -C kreato && sudo chroot kreato 
      - name: Do other things?
        run: git clone https://github.com/${{ github.repository }} && cd ${{ github.event.repository.name }} && git checkout ${{ github.ref_name }} && chmod +x ./build-everything.sh && ./build-everything.sh  
